name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:40
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf -y install rpm-build dnf-utils wget
          dnf -y builddep SPECS/kernel.spec

      - name: Download Kernel Tarball
        run: |
          TARBALL=$(rpmspec --parse SPECS/kernel.spec | grep Source0 | cut -b 10-)
          wget -P SOURCES https://cdn.kernel.org/pub/linux/kernel/v6.x/${TARBALL}

      - name: Build Kernel
        run: |
          ./TOOLS/build.sh -ba SPECS/kernel.spec
